name: metrics
on:
  schedule: [{cron: "0 0-23/8 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Paris
          base: header
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_notable: yes
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact
          filename: metrics.svg
          config_display: large
