name: metrics
on:
  schedule: [{cron: "0 0-23/8 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Paris
          base: header
          plugin_languages: yes
          plugin_notable: yes
          plugin_followup: yes
          plugin_followup_archived: no
          plugin_topics: yes
          plugin_topics_mode: labels
          plugin_topics_sort: activity
          filename: metrics.svg
          config_display: large
